{% set name = "schemainspect" %}
{% set version = "3.1.1663587362" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemainspect-{{ version }}.tar.gz
  sha256: a295ad56f7a19c09e5e1ef9f16dadbf6392e26196cb5f05b5afe613c99ce7468

build:
  entry_points:
    - schemainspect = schemainspect:do_command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - sqlalchemy
    - sqlbag

test:
  imports:
    - schemainspect
  commands:
    - pip check
    - schemainspect --help
  requires:
    - pip

about:
  home: https://github.com/djrobstep/schemainspect
  summary: Schema inspection for PostgreSQL (and possibly others)
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
